### ISSUE TITLE
Full support for all additional action header values on dir and list APIs

### ISSUE THREAD

**Issue by bobbyjball3** [akamai-open/NetStorageKit-Node#2]
After using my own rewrite of list API call and discovering the difference in behavior with dir, it's clear that full support for all of the action headers for dir _(e.g. prefix, start, max_entries, etc.)_ and list are needed for customers like myself with huge numbers of objects in NetStorage buckets and directories. 

list already accepts an object with the max_entries action header from my previous pull request. But we should probably add support to dir and make the allowable action headers more feature-complete with the NS API. We'll have to be careful not to break functionality against NS3 though since some of the supported entries differ between NS3/4.

**Comment by bobbyjball3** [comment]
I'll add that I'm happy to fork and work on this since I've already modified some of the code in a local repo for my own testing.

**Comment by AstinCHOI** [comment]
Dear, @bobbyjball3

Thanks for your idea and test. Please comment it after testing !
I really appreciate your contribution.

**Comment by bobbyjball3** [comment]
@AstinCHOI Great. I'll mock something up and test tomorrow.

**Comment by bobbyjball3** [comment]
@AstinCHOI For the dir and list netstorage methods, I'm considering something like the following. By doing this, though it's more complicated, we maintain compatibility for just passing the path instead of verbose options. Since most people won't need verbose options, this keeps the usability high, while allowing for more advanced users to use the more advanced options. 

````Javascript
dir(opts, callback) {
  if (typeof opts === 'object') {
    // set options from object
  } else if (typeof opts === 'string') { 
    // set url from string
  } else {
    // throw an error here because we couldn't sort it out
  }

  //actually make request
}
````

**Comment by AstinCHOI** [comment]
@bobbyjball3 It looks good !

**Comment by bobbyjball3** [comment]
@AstinCHOI I've got this functionality added in [my most recent branch](https://github.com/bobbyjball3/NetStorageKit-Node/commits/dir-list-options). All tests pass, and I'll be submitting a PR soon.

Would you mind assigning this issue to me and adding the enhancement tag?

**Comment by bobbyjball3** [comment]
I believe that [PR 3](#3) should close out this issue out once reviewed.

**Comment by AstinCHOI** [comment]
I really appreciate your contribution !
